// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pemalvnrwvkegmuxxlju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlbWFsdm5yd3ZrZWdtdXh4bGp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NTYyODcsImV4cCI6MjA3MTEzMjI4N30.hxfIqC38_f3UPXJwtkEaULgS6Hnc642WfBkOm-E5Jsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});